import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    padding: 20,
  },
  header: {
    marginTop: 20,
    marginBottom: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  greeting: {
    fontSize: 42,
    fontWeight: "700",
    color: "#6B7B28",
    marginBottom: 5,
  },
  welcomeText: {
    fontSize: 38,
    fontWeight: "700",
    color: "#6B7B28",
  },
  statusBadge: {
    backgroundColor: "#E8EFBE",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#8BA339",
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7B28",
  },
  batteryCard: {
    backgroundColor: "#8BA339",
    borderRadius: 24,
    padding: 25,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#8BA339",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 5,
  },
  batteryContent: {
    flex: 1,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 15,
  },
  cardTitle: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  batteryPercentage: {
    fontSize: 72,
    fontWeight: "800",
    color: "#FFFFFF",
    lineHeight: 75,
    marginBottom: 5,
  },
  estimatedContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  estimatedDistance: {
    fontSize: 15,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  batteryBar: {
    width: 50,
    height: 180,
    backgroundColor: "rgba(232, 239, 190, 0.3)",
    borderRadius: 25,
    overflow: "hidden",
    marginLeft: 20,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  batteryFill: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#E8EFBE",
    borderRadius: 23,
  },
  // Voltage Info Card - Full Width Enhanced
  voltageInfoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 25,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  voltageHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  voltageIconLarge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#E8EFBE",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#8BA339",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  voltageHeaderText: {
    flex: 1,
  },
  voltageLabel: {
    fontSize: 14,
    color: "#999999",
    fontWeight: "500",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  voltageValue: {
    fontSize: 48,
    fontWeight: "800",
    color: "#6B7B28",
    lineHeight: 52,
  },
  voltageStatusContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  voltageStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#E8EFBE",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  voltageStatusText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B7B28",
  },
  voltageRange: {
    alignItems: "flex-end",
  },
  voltageRangeLabel: {
    fontSize: 11,
    color: "#999999",
    fontWeight: "500",
    marginBottom: 2,
  },
  voltageRangeValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6B7B28",
  },
  voltageProgress: {
    marginTop: 8,
  },
  voltageProgressBar: {
    height: 8,
    backgroundColor: "#F0F0F0",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  voltageProgressFill: {
    height: "100%",
    width: "45%",
    backgroundColor: "#8BA339",
    borderRadius: 4,
  },
  voltageProgressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  voltageProgressLabel: {
    fontSize: 10,
    color: "#999999",
    fontWeight: "500",
  },
  chartCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  chartHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  chartTitle: {
    fontSize: 20,
    color: "#6B7B28",
    fontWeight: "700",
    marginBottom: 2,
  },
  chartSubtitle: {
    fontSize: 12,
    color: "#999999",
    fontWeight: "500",
  },
  liveIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F0F9FF",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#22C55E",
  },
  liveText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#22C55E",
  },
  chart: {
    marginVertical: 8,
    borderRadius: 16,
  },
  chartFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
  },
  chartLegend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#8BA339",
  },
  legendText: {
    fontSize: 12,
    color: "#666666",
    fontWeight: "500",
  },
  chartRange: {
    fontSize: 11,
    color: "#999999",
    fontWeight: "500",
  },
  spacer: {
    height: 100,
  },
});

export default styles;
